# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HQModelDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HQModelDemo
pod 'FMDB/SQLCipher', '~> 2.6'
pod 'YYModel', '~> 1.0.4'
pod 'JSONModel', '~> 1.7.0'

end
